clouddrive:
  mount_path: /mnt/smb/192.168.1.100#myShare/CloudDrive/115
extension_monitoring:
  bdmv: true
  iso: true
  m2ts: false
  mkv: false
  mp4: false
general:
  auto_start: false
  heart_rate: 500
  log_level: INFO
mapping_paths:
- enable: true
  mapping_type: media
  source: /mnt/smb/192.168.1.100#myShare/CloudDrive/115
  target: /bp_path
- enable: true
  mapping_type: strm
  source: /mnt/smb/192.168.1.100#myShare/strm
  target: /volume1/myShare/strm
notification:
  endpoint: http://192.168.1.100:7507/play
  timeout_seconds: 15
zidoo:
  api_path: /ZidooVideoPlay/getPlayStatus
  ip: 192.168.1.110
